version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: expiry_tracker_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: expiry_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - expiry_tracker_network

  app:
    build: .
    container_name: expiry_tracker_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      GO_ENV: dev
      POSTGRES_USER: postgres
      POSTGRES_PW: postgres
      POSTGRES_DB: expiry_tracker
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db
      SECRET: uu5pveql
      PORT: 8080
      API_DOMAIN: localhost
    depends_on:
      - db
    networks:
      - expiry_tracker_network
    volumes:
      - ./:/app
      - /app/tmp

volumes:
  postgres_data:

networks:
  expiry_tracker_network:
    driver: bridge